import { Metadata } from 'next';
import NavBar from './Components/NavBar/page'
import Dashboard from './Components/Dashboard/page'
import Dasboard2 from './Components/Dashboard-2/page'
import SearchBar from './Components/SearchBarApi/page'


export const metadata: Metadata = {

  title: "Main Home",
  description: "Generated by create next app",
  icons: "https://resources.finalsite.net/images/v1644518566/landon/tefnda5v8covxmyjxopc/Landon_Body_Color.png"

};

export default function Home() {

 
  return (
    <>
    <main className='w-full h-screen bg-white'>

    <NavBar />
    <Dashboard />

    </main>

    <div className="w-full h-screen bg-black p-10">

    <Dasboard2 />

    </div>

    <SearchBar />


    </>
  );
}
